Fix SPEC CPU2006 config file for AT 12.0 (GCC 8)
Since GCC 8.1, gfortran issues an error "when an actual argument
contains too few elements for a dummy argument" [1].  This behaviour
breaks the build of 416.gamess, with error messages similar to:

    ecp.fppized.f:402:15:

           CALL ZFN(ZFNLM,NPNP-1,ZLM,LMF,LMX,LMY,LMZ)
                   1
    Error: Actual argument contains too few elements for dummy argument 'zfnlm' (121/125) at (1)

as described more thoroughly in bug report #549 [2].

This patch adds gfortran's '-std=legacy' option (via 'FPORTABILITY') to
the configuration file for SPEC CPU2006 tests, as suggested by the
release notes for GCC 8.1 [1].

[1] https://gcc.gnu.org/gcc-8/changes.html#fortran

[2] https://github.com/advancetoolchain/advance-toolchain/issues/549

Signed-off-by: Gabriel F. T. Gomes <gabriel@inconstante.eti.br>