Fix binutils build with GCC 11
GCC 11 started throwing the following warning when building binutils
stage 2:

./gold/plugin.cc:528:10: error: ‘char* strncpy(char*, const char*, size_t)’
specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  528 |   strncpy(tempdir, dir_template, len);
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./gold/plugin.cc:526:22: note: length computed here
  526 |   size_t len = strlen(dir_template) + 1;
      |                ~~~~~~^~~~~~~~~~~~~~

The code causing the error is not necessarily wrong, we can ignore this
warning for the time being.

Signed-off-by: Matheus Castanho <msc@linux.ibm.com>