next: Suppress deprecated declaration error on binutils
Since the deprecation of mallinfo in favor of mallinfo2 in glibc (glibc
commit 30e5069c7) binutils stage 2 has been failing to build:

sources/binutils/gold/main.cc:294:36: error: ‘mallinfo mallinfo()’ is deprecated
[-Werror=deprecated-declarations]
  294 |       struct mallinfo m = mallinfo();

There is already a bug report upstream [1], but development on gold has
been slow lately. While this is not fixed upstream, let's suppress this
warning to let our builds succeed.

[1] https://sourceware.org/bugzilla/show_bug.cgi?id=26585

Signed-off-by: Matheus Castanho <msc@linux.ibm.com>